Repository bookshelf/bookshelf, pull requests merged in 2018-03, with the labels that each got.

#1625 Pagination plugin ignores transactions
  src/plugins/pagination.js
Labels: bug, plugin, transactions, weak/no tests

#1776 Add test for fetchPage inside a transaction
  test/integration/plugins/pagination.js
Labels: plugin, tests, transactions

#1777 Remove second argument of model destroyed event
  src/model.js
Labels: change, docs, events

#1778 Increase timeout of the large arrays test
  test/base/tests/collection.js
Labels: tests

#1779 Make require: true the default for deleting models
  src/model.js
  test/integration/model.js
Labels: change, events

#1784 Fix inconsistent timestamp values
  src/base/model.js
  src/collection.js
  src/constants.js
  src/model.js
  src/relation.js
  test/integration/model.js
Labels: bug, timestamps

#1768 Events are triggered sequentially when the handlers execute async code
  src/base/events.js
  test/integration/model.js
Labels: change, events

#1769 Added test that `parentId` is not undefined when using `fetchAll` with relations
  test/integration/relations.js
Labels: Investigating, relations

#1788 Use a different method to check for Knex on Bookshelf construction
  src/bookshelf.js
  test/.eslintrc
  test/index.js
Labels: bug

#1790 Remove unnecessary processor plugin methods
  src/plugins/processor.js
  test/integration/plugins/processor.js
Labels: change, plugin

#1796 Fix timestamps set with Invalid Date in some cases
  src/base/model.js
  test/integration/model.js
  test/integration/plugins/pagination.js
Labels: bug, timestamps

#1797 Fix incorrect data types and undocumented Model property
  src/base/collection.js
  src/base/model.js
  src/bookshelf.js
  src/collection.js
  src/model.js
  src/relation.js
Labels: docs

#1798 Clean up automatic timestamps feature
  src/base/model.js
  src/model.js
  test/integration/model.js
  test/unit/sql/model.js
Labels: change, timestamps
