Repository bookshelf/bookshelf, pull requests merged in 2018-12, with the labels that each got.

#1918 Fix withRelated not always grouping properly for binary IDs
  lib/base/collection.js
  lib/relation.js
  test/base/tests/collection.js
  test/integration/helpers/migration.js
  test/integration/helpers/objects.js
  test/integration/relations.js
Labels: bug, relations

#1926 Pass proper context
  lib/bookshelf.js
Labels: bug, knex

#1928 Fix crash when using groupBy with table qualifier
  lib/plugins/pagination.js
  test/integration/plugins/pagination.js
Labels: bug

#1930 Update ESLint to the latest version
  .eslintrc
  .eslintrc.json
  .travis.yml
  lib/base/model.js
  package.json
Labels: dependencies

#1931 Update knex to the latest version
  README.md
  package.json
Labels: dependencies
