Repository bookshelf/bookshelf, pull requests merged in 2018-04, with the labels that each got.

#1810 Add row-level locking options
  src/bookshelf.js
  src/collection.js
  src/model.js
  src/sync.js
  test/integration/model.js
  test/unit/sql/sync.js
Labels: feature request, transactions

#1800 Fix performance of including relationships
  src/relation.js
  test/integration/relation.js
Labels: performance, relations

#1821 Update function comment in eager.js
  src/base/eager.js
Labels: docs

#1820 Fix timestamp() setting a key named "null" in some cases
  src/base/model.js
  test/integration/model.js
Labels: bug, timestamps

#1826 Undeprecate options.date argument to timestamp
  src/base/model.js
  test/integration/model.js
Labels: change, timestamps

#1829 Update to node 10 in .travis.yml
  .travis.yml
Labels: greenkeeper, tests

#1830 Make collection iterable using for of loops
  src/base/collection.js
  test/base/tests/collection.js
Labels: feature request

#1831 Fix incorrect docs for collection:fetching event
  src/model.js
Labels: docs, events
