Repository bookshelf/bookshelf, pull requests merged in 2018-11, with the labels that each got.

#1907 upgrade husky to v1
  package.json
Labels: dependencies

#1909 Documentation website redesign
  .gitignore
  .npmignore
  CHANGELOG.md
  README.md
  docs/api.html
  docs/bookshelf.js.html
  docs/images/bookshelf-icon-inverted.svg
  docs/images/favicon.ico
  docs/index.html
  docs/lib_base_collection.js.html
  docs/lib_base_events.js.html
  docs/lib_base_model.js.html
  docs/lib_bookshelf.js.html
  docs/lib_collection.js.html
  docs/lib_model.js.html
  docs/lib_plugins_case-converter.js.html
  docs/lib_plugins_pagination.js.html
  docs/lib_plugins_processor.js.html
  docs/lib_relation.js.html
  docs/lib_sync.js.html
  docs/scripts/linenumber.js
  docs/scripts/main.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/main.css
  docs/tutorial-associations.html
  docs/tutorial-many-to-many.html
  docs/tutorial-models.html
  docs/tutorial-one-to-many.html
  docs/tutorial-one-to-one.html
  docs/tutorial-parse-and-format.html
  docs/tutorial-polymorphic.html
  docs/tutorials.html
  lib/plugins/case-converter.js
  package.json
  scripts/gh-pages.sh
  scripts/jsdoc.config.json
  scripts/jsdoc.sh
  scripts/postpublish.sh
  tutorials/index.md
  tutorials/many-to-many.md
  tutorials/models.md
  tutorials/tutorials.json
  tutorials/tutorials.md
Labels: docs

#1876 Create previousAttributes using a deep clone of attributes
  lib/base/model.js
  test/integration/json.js
Labels: bug

#1917 Add events tutorial to documentation
  .github/CONTRIBUTING.md
  lib/base/events.js
  lib/collection.js
  lib/model.js
  lib/sync.js
  scripts/jsdoc.sh
  scripts/postpublish.sh
  tutorials/events.md
  tutorials/models.md
  tutorials/tutorials.json
Labels: docs
