Repository bookshelf/bookshelf, pull requests merged in 2018-02, with the labels that each got.

#1760 Set model.id if attributes contain a parsed version of idAttribute
  src/base/model.js
  test/integration/model.js
Labels: bug

#1761 Improve docs about running tests
  .github/CONTRIBUTING.md
  README.md
Labels: docs

#1638 add withSchema support
  src/sync.js
Labels: feature request, weak/no tests

#1766 Add tests for withSchema option
  test/integration/helpers/index.js
  test/integration/helpers/inserts.js
  test/integration/helpers/migration.js
  test/integration/helpers/objects.js
  test/integration/model.js
  test/unit/sql/sync.js
Labels: tests

#1770 Only request returning attribute if client supports returning
  src/sync.js
Labels: change
