Repository bookshelf/bookshelf, pull requests merged in 2019-02, with the labels that each got.

#1950 Count unique occurrences of a column when using distinct to calculate pagination details
  lib/plugins/pagination.js
  test/integration/plugins/pagination.js
Labels: bug, plugin

#1951 Update and fix a lot of doclets
  .github/CONTRIBUTING.md
  README.md
  lib/base/collection.js
  lib/base/events.js
  lib/base/model.js
  lib/base/relation.js
  lib/bookshelf.js
  lib/collection.js
  lib/model.js
  lib/plugins/pagination.js
  lib/relation.js
  lib/sync.js
  test/integration/plugins/pagination.js
  tutorials/models.md
Labels: docs

#1955 Fix JSON tests on PostgreSQL 10+
  package.json
  test/integration/helpers/json/supported.js
  test/integration/json.js
Labels: bug, tests

#1956 Remove old deprecated code
  lib/base/collection.js
  lib/base/eager.js
  lib/base/events.js
  lib/base/promise.js
  lib/bookshelf.js
  lib/collection.js
  lib/eager.js
  lib/helpers.js
  lib/model.js
  lib/relation.js
  lib/sync.js
  package.json
  test/index.js
Labels: change
