Repository bookshelf/bookshelf, pull requests merged in 2019-07, with the labels that each got.

#1991 Update dependencies
  .travis.yml
  package.json
Labels: dependencies

#1992 Move pagination plugin to core
  .eslintrc.json
  lib/bookshelf.js
  lib/collection.js
  lib/helpers.js
  lib/model.js
  lib/plugins/pagination.js
  test/integration.js
  test/integration/collection.js
  test/integration/model.js
  test/integration/plugins/pagination.js
Labels: feature request, refactor

#1993 Move visibility plugin to core
  README.md
  lib/base/model.js
  lib/bookshelf.js
  lib/plugins/visibility.js
  test/integration.js
  test/integration/model.js
  test/integration/plugins/visibility.js
  test/unit/sql/model.js
Labels: feature request, refactor

#1994 chore(package): update lint-staged to version 9.1.0
  package.json
Labels: dependencies

#1996 Move registry plugin to core
  README.md
  lib/base/model.js
  lib/bookshelf.js
  lib/collection.js
  lib/errors.js
  lib/model.js
  lib/plugins/processor.js
  lib/plugins/registry.js
  lib/relation.js
  lib/sync.js
  test/base/tests/collection.js
  test/index.js
  test/integration.js
  test/integration/collection.js
  test/integration/helpers/inserts.js
  test/integration/helpers/json/inserts.js
  test/integration/helpers/json/migration.js
  test/integration/helpers/migration.js
  test/integration/model.js
  test/integration/plugins/registry.js
  test/integration/relations.js
  test/unit/bookshelf.js
  test/unit/sql/model.js
  tutorials/events.md
  tutorials/many-to-many.md
  tutorials/models.md
  tutorials/one-to-many.md
  tutorials/one-to-one.md
  tutorials/parse-and-format.md
  tutorials/polymorphic.md
Labels: feature, refactor
