Repository bookshelf/bookshelf, pull requests merged in 2019-09, with the labels that each got.

#2012 Refresh model attributes after a save operation
  README.md
  lib/model.js
  lib/sync.js
  test/integration/collection.js
  test/integration/model.js
  test/unit/model.js
Labels: change, feature

#2013 Update count methods docs
  lib/bookshelf.js
  lib/collection.js
  lib/model.js
Labels: docs

#2011 Fix throwing of constructor function instead of ModelNotResolvedError
  lib/errors.js
  test/unit/bookshelf.js
Labels: bug

#2014 Improve documentation related to debug mode
  README.md
  lib/bookshelf.js
  lib/collection.js
  lib/model.js
Labels: docs

#2021 Update all dev dependencies
  package-lock.json
  package.json
Labels: dependencies
