Repository bookshelf/bookshelf, pull requests merged in 2019-08, with the labels that each got.

#1998 The word 'the' is written twice, one after another
  README.md
Labels: docs

#2000 Remove all built-in plugins
  README.md
  lib/base/model.js
  lib/base/relation.js
  lib/bookshelf.js
  lib/plugins/case-converter.js
  lib/plugins/processor.js
  lib/plugins/virtuals.js
  test/integration.js
  test/integration/plugin.js
  test/integration/plugins/case-converter.js
  test/integration/plugins/processor.js
  test/integration/plugins/virtuals.js
Labels: change, plugin

#2001 Change Collection#where so it behaves like Model#where
  lib/base/collection.js
  lib/collection.js
  test/base/tests/collection.js
  test/integration/collection.js
  test/integration/model.js
Labels: change

#2002 Test chaining Collection#orderBy() with fetchPage()
  test/integration/collection.js
Labels: tests

#2003 Remove unused code
  package.json
  scripts/build.js
  test/base/README.md
  test/base/index.js
  test/index.js
  test/integration/index.js
  test/unit/collection.js
  test/unit/events.js
  test/unit/model.js
  test/unit/sync.js
Labels: refactor

#2005 Remove some Model and Collection lodash based methods
  lib/base/collection.js
  lib/base/model.js
  test/integration/relations.js
  test/unit/collection.js
Labels: change
