Repository bookshelf/bookshelf, pull requests merged in 2020-06, with the labels that each got.

#2072 Add support for knex 0.21.x
  .travis.yml
  package-lock.json
  package.json
Labels: change, dependencies

#2070 Add option to control auto refresh after save
  lib/model.js
  lib/sync.js
  test/integration/model.js
Labels: feature

#2078 Update some dependencies
  package-lock.json
  test/integration/relations.js
Labels: dependencies

#2079 Add more Collection#fetch integration tests
  test/integration/collection.js
Labels: tests
